### ISSUE TITLE
Confirmed working QT-07S manufactured by Qoto in Tasmota

### ISSUE THREAD

**Issue by fcsegalla** [blakadder/zigbee#1024]
I created a Zigbee plugin file and it is working in Tasmota 12.5.

This is a soil sensor for temperature and humidity, i used a GMX-01 to test

File content:

#Z2Tv1
# Soil Sensor GMX-01
# https://zigbee.blakadder.com/Yieryi_THE01840.html
:TS0601,_TZE200_myd45weu
EF00/0203=0405/0000,mul:100 # humidity
EF00/0205=0402/0000,mul:100 # temperature
EF00/020F=0001/0021,mul:2  # batterypercentage
EF00/040E=0001/0035  # BatteryAlarmMask (not completely sure)

**Comment by blakadder** [comment]
there is an edit button to add that
