### ISSUE TITLE
device on the list shows support for deconz and zha but it says otherwise when click on details

### ISSUE THREAD

**Issue by accelle17** [blakadder/zigbee#108]
Here's the sample: https://zigbee.blakadder.com/Philips_1743530P7.html
It shows zigbee2mqtt, iobroker and zha on the details but on a list (https://zigbee.blakadder.com/lights.html) it shows support for deconz and tasmota too. On the github page, it only shows iob, z2m.

**Comment by blakadder** [comment]
Thanks! Fixed it!
