### ISSUE TITLE
Config for GiEX_QT06

### ISSUE THREAD

**Issue by peepshow-21** [blakadder/zigbee#1125]
Hi,

looking here;
https://zigbee.blakadder.com/GiEX_QT06.html

I have copied this config to my bridge;
https://zigbee.blakadder.com/assets/configs/TZE200_sh1btabb.zb (I've named file TZ200.zb)

It now shows battery and basic info for (Water Meter) as;
![image](https://github.com/blakadder/zigbee/assets/42150988/01ee7a2a-715e-401c-9c79-be7b962f59e7)

I can open/close value with;
```
15:08:38.620 CMD: zbsend {"device":"0xc629","write":{"waterstate":0}}
15:08:38.631 MQT: stat/zigbee_bridge/RESULT = {"ZbSend":"Done"}
15:08:38.886 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0xC629":{"Device":"0xC629","Name":"Water Meter","CurrentTemperature":0,"Endpoint":1,"LinkQuality":182}}}
15:08:39.038 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0xC629":{"Device":"0xC629","Name":"Water Meter","WaterState":0,"Endpoint":1,"LinkQuality":178}}}
```

So all good to here.

However, is it possible to show if the value is open or not in the GUI, in the same way as the Greenhouse can report temp?

The, can you open/close it from the GUI via some config changes too?

Thanks

**Comment by blakadder** [comment]
That's a question for [Tasmota support](https://tasmota.github.io/docs/#join-our-community)
