### ISSUE TITLE
[BUG] Lidl Melinera LED String Lights HG06467 website does not match code

### ISSUE THREAD

**Issue by Hedda** [blakadder/zigbee#136]
Bug? Lidl Melinera LED String Lights HG06467 website does not match code:

https://zigbee.blakadder.com/Lidl_HG06467.html

https://github.com/blakadder/zigbee/blob/master/_zigbee/Lidl_HG06467.md

Code is correct that only z2m is compatible today. 

ZHA and Tasmota are not yet compatible with this device.

**Comment by blakadder** [comment]
have you tested it with ZHA or Tasmota?

**Comment by Hedda** [comment]
@blakadder I do not own it myself but other many ZHA users (and developers) report it does not work with ZHA yet, see:

https://github.com/zigpy/zha-device-handlers/issues/604

https://community.home-assistant.io/t/lidl-has-released-a-bunch-of-inexpensive-zigbee-3-0-certified-smart-devices/248825/16

https://community.home-assistant.io/t/silvercrest-lidl-smarthome/243561/123

As you can read and link to Zigbee2MQTT and deCONZ development discussions it is a very non-standard device and it it is designed it will not work by default with any Zigbee solution before some development work has been done.

So the same goes for Tasmota2Zigbee where it is not supported yet either:

https://github.com/arendst/Tasmota/issues/9051

It will however soon work in an upcoming deCONZ version as the development work has been done there. See:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3716

Summery and conclusion; So far it is only supported in the very latest Zigbee2MQTT, however even in it they say it is still buggy:

https://github.com/Koenkk/zigbee-herdsman-converters/issues?q=HG06467

**Comment by Hedda** [comment]
Just to clarify; it is not supported by Tasmota either as of yet, see https://github.com/arendst/Tasmota/issues/9051

It is only supported by Zigbee2MQTT.

deCONZ support is however in the pipeline.

**Comment by blakadder** [comment]
That issue is not relevant to this discussion

**Comment by CopyCat73** [comment]
For a device that can adjust colors and has multiple scenes, I wouldn't define the ability to switch it on and off as "working". I bought it and am willing to assist in making it compatible with tasmota, but the low level commands through my sonoff zigbee bridge are giving me a headache..
