### ISSUE TITLE
Ikea motion sensor links for z2m are not working

### ISSUE THREAD

**Issue by torusJKL** [blakadder/zigbee#164]
The links on the following pages do not link to the correct zigbee2mqtt.io page.
https://github.com/blakadder/zigbee/blob/master/_zigbee/Ikea_E1745.md
https://github.com/blakadder/zigbee/blob/master/_zigbee/Ikea_E1525.md

They should both link to 
https://www.zigbee2mqtt.io/devices/E1525_E1745.html

**Comment by blakadder** [comment]
fixed
