### ISSUE TITLE
New brand/devices submitted but not avaiable

### ISSUE THREAD

**Issue by pipiche38** [blakadder/zigbee#170]
I have almost 3 weeks ago submitted several devices from CASA.IA 

Here is the shop

ALL of the Zigbee devices have been certified on ZiGate with Domoticz plugin.

Unfortunately it seems that the new submission (as it was referring to a new brand are not yet processed ).

Is there any think I miss in the process ?

**Comment by blakadder** [comment]
nope, just holidays and real life being in the way

**Comment by pipiche38** [comment]
Ok . good no issue then ;-)

And happy new year and thanks for what you are doing
