### ISSUE TITLE
TS0042 by _TZ3400_keyjhapk WRONG compatibility on ZHA

### ISSUE THREAD

**Issue by DavidFFerreira** [blakadder/zigbee#187]
I did bought this https://bit.ly/2XTGtWn on alli link and it didnt work. Already open a issue on github https://bit.ly/3isrBrl . Please change the compatibility

**Comment by blakadder** [comment]
Your issue lists a different manufacturer code

**Comment by DavidFFerreira** [comment]
yup, but I did merge the code that already have my manufactor.... @blakadder

**Comment by DavidFFerreira** [comment]
@blakadder the link and the seller was from the alliexpress link that you put in zha compatibility page....sooo not credible

**Comment by blakadder** [comment]
I cannot control which version the seller will send to you

**Comment by DavidFFerreira** [comment]
@blakadder thats why you should not put it in compatibility, because its a lottery
