### ISSUE TITLE
Taking in consideration Plugin and Box

### ISSUE THREAD

**Issue by pipiche38** [blakadder/zigbee#20]
I like much your Database and how easy it is to add product compatibility.

I wonder if it would not make sense to add the notion of Box ( Jeedom, Domoticz, HA ...) and the compatibility as well.

For instance, in the case of Zigate, the product can be compatible with Zigate, but still you have to perform some work on the plugin side to get fully working.

**Comment by blakadder** [comment]
That's the problem of the gateway and its implementation with the home automation solution

**Comment by pipiche38** [comment]
You right, but I suspect that there is a mixed between Gateway and Coordinator.

Zigate as such is a Coordinator and required a Gateway App in order to work. 
You have for instance
Domoticz-Zigate for Domoticz
Zigate for Jeedom
Abeille for Jeedom
homeassistant-zigate for HA

As for instance you have Zigbee Home Automation which integrate a number of Coordinator with HA.

**Comment by blakadder** [comment]
In that case I can focus only on Domoticz or remove Zigate completely due to the complexity involved
