### ISSUE TITLE
Legend for the `Supports` attributes

### ISSUE THREAD

**Issue by afoeder** [blakadder/zigbee#249]
So, looking at https://zigbee.blakadder.com/Busch_Jaeger_6736.html there is a `supports` item `action`. I wonder what that means. Can we or do we have an explanation of those? Is there a list of "allowed" attributes and a map to their implementation and capabilities? For example also `smoke` etc…

Thanks!

**Comment by afoeder** [comment]
Hi @blakadder could you please at least say if you agree that this would be nice-to-have etc.? If you could tell me more about it I'd be happy to provide a PR.

**Comment by blakadder** [comment]
https://www.zigbee2mqtt.io/devices/6735_6736_6737.html#action-values

**Comment by afoeder** [comment]
yes that section is literally my contribution :) But how would we explain it to typical website visitors (like I was back then when I created this issue) what to do with the `supports` items?

**Comment by blakadder** [comment]
It supports actions, actions vary depending on the gateway used and most solutions present the actions in their own way. 

If you can find a unified way of meaningfully presenting that let me know.

**Comment by afoeder** [comment]
would you reopen it and assign it to me please, I'll take care and provide a PR

**Comment by blakadder** [comment]
state of an issue does not prevent you from making a PR
