### ISSUE TITLE
[REQUEST] Zigbee Stack / Firmware column for Zigbee coordinators

### ISSUE THREAD

**Issue by Hedda** [blakadder/zigbee#29]
Please consider adding a column for Zigbee Stack / Firmware to the Zigbee coordinators section:

https://zigbee.blakadder.com/coordinators.html

Suggest adding additional columns to the database of Zigbee coordinators to make comparing easier.

This is as many different manufacturers use the same or similar Zigbee MCU radio chips or modules in their products and while some use the same Zigbee MCU radio chips they might run different Zigbee stacks and firmware.

For example, some Telegesis ETRX357 product series are based on the same type of ETRX35x chip family as Elelabs Zigbee products and Nortek HUSBZB-1 but use different Zigbee stack/firmware. And some MCU chips, like 

- MCU radio chip/module manufacturer (ex. Silicon Labs, Texas Instruments, Digi International, dresden elektronik, ZiGate, and Nordic Semiconductor)
- MCU radio chip/module model (ETRX357, CC2530, CC2531, CC2538, CC2652R, CC2652P, CC1352P)
- Zigbee Version (ZHA 1.2, Zigbee PRO, or Zigbee 3.0 are the three most common versions)
- Zigbee Stack / Firmware, including version as for example both Silicon Labs and Texas Instruments have separate Zigbee stack versions for ZHA 1.2, Zigbee PRO, or Zigbee 3.0. As Silicon Labs has "EmberZNet PRO" (for Zigbee PRO) and "EmberZNet 3.0" (for Zigbee 3.0) , and Texas Instruments as Z-Stack 1.2 (for ZHA 1.2) and Z-Stack 3.0 (for Zigbee 3.0).

See requests/suggestions:

https://github.com/blakadder/zigbee/issues/26
https://github.com/blakadder/zigbee/issues/27
https://github.com/blakadder/zigbee/issues/28
https://github.com/blakadder/zigbee/issues/29

**Comment by blakadder** [comment]
you're welcome to create a PR
