### ISSUE TITLE
Broken Z2M link for devices with slash `/` in model name

### ISSUE THREAD

**Issue by aesedepece** [blakadder/zigbee#290]
See the [SOHAN Electric RDCBC/Z page](https://zigbee.blakadder.com/Sohan_RDCBC.html) for example.

The model name (`RDCBC/Z`) contains a slash (`/`), but the Z2M website uses underscore (`_`) for the sake of not breaking the URL.

This causes the Z2M link to be broken on the Blakadder website:
- Current broken URL: https://www.zigbee2mqtt.io/devices/RDCBC/Z.html
- Actual Z2M URL: https://www.zigbee2mqtt.io/devices/RDCBC_Z.html

To fix this, I think this website should substitute slashes for underscores on the fly when generating the Z2M URLs.

**Comment by blakadder** [comment]
fixed

**Comment by aesedepece** [comment]
Man that was fast.

Kudos for the website!

**Comment by aesedepece** [comment]
@blakadder ooops I think it's now broken for a different reason: an extra whitespace before `.html`

**Comment by blakadder** [comment]
was too fast :D removed the space now

**Comment by aesedepece** [comment]
It's working now. Thanks!
