### ISSUE TITLE
OK to add "OpenHAB" ("openHAB Zigbee Binding") compatibility? 

### ISSUE THREAD

**Issue by Gamester17** [blakadder/zigbee#301]
Would it be OK to add "OpenHAB" ("openHAB Zigbee Binding") compatibility? 

https://www.openhab.org/addons/bindings/zigbee/

openHAB Zigbee Binding supports Zigbee devices via different USB sticks.

https://www.openhab.org/addons/bindings/zigbee/#supported-coordinators

**Comment by blakadder** [comment]
it is under consideration but the supported devices list is awfully short

can i expect openHab community input for the list of supported devices?

is there an easy way to track newly added devices to the supported list?

**Comment by Gamester17** [comment]
> can i expect openHab community input for the list of supported devices?

I think so, as long as they are aware that your database accepts compatibility PRs for openHAB. That was even mentioned here:

https://community.openhab.org/t/testing-popular-zigbee-devices-and-coordinators/121237/

openHAB community forum by the way has a "zigbee" tag which is suppse to be used for the official openHAB Zigbee Binding:

https://community.openhab.org/tag/zigbee

That "zigbee" tagging is example different from other Zigbee implementations such as zigbee2mqtt and deconz

https://community.openhab.org/tag/zigbee2mqtt

https://community.openhab.org/tag/deconz

> is there an easy way to track newly added devices to the supported list?

Somewhat yes as the source code for the official openHAB Zigbee Binding is maintained in its own repository on GitHub here:

https://github.com/openhab/org.openhab.binding.zigbee/

That in turn dependent on Z-Smart Systems ZigBee library so some lower-leveled fixes will need to get applied there instead:

https://github.com/zsmartsystems/com.zsmartsystems.zigbee

However please note that as you probably already understand, just as with other Zigbee implementations all devices that follow the standard ZHA and ZLL specifications should just work without support having to be specifically added to unique devices. So can safely assume that at least all basic Zigbee lights such as LED bulbs and relays (power-plugs) will work.

**Comment by blakadder** [comment]
Looks like the community is not really interested in such a list https://community.openhab.org/t/supported-zigbee-devices-list/122479
