### ISSUE TITLE
Moes_ZSS-ZK-THL.md should be edited, because ZHA is not really working with the device

### ISSUE THREAD

**Issue by almico** [blakadder/zigbee#363]
As described [here](https://github.com/zigpy/zha-device-handlers/issues/961), this device is next to unusable with the current ZHA.
The device seems to reset every 150 seconds, often reports zeroes, sometimes doesn't update at all, and, finally, it can enter some emergency state (at least, this is what the "!" seems to suggest).

**Comment by blakadder** [comment]
there's an edit option on the page
