### ISSUE TITLE
IKEA E1812 shortcut

### ISSUE THREAD

**Issue by MilewskiPawel** [blakadder/zigbee#374]
This is only trigger, no brighteness control possible.
Zigbee recognise LQ and batterry % only. No action for this entity

**Comment by blakadder** [comment]
device page doesn't state bightness support

**Comment by MilewskiPawel** [comment]
Thx man for fast reply but here https://github.com/blakadder/zigbee/blob/master/_zigbee/Ikea_E1812.md is described it supports action and battery- recognise LQ and batterry % only. No action for this entity. Sorry if I dent get it clear
![image](https://user-images.githubusercontent.com/22003968/129858244-196a0732-442e-4bb4-b37c-dbebb0b4c540.png)
![image](https://user-images.githubusercontent.com/22003968/129858313-cd262636-60b6-4c5a-aab0-9692e6bb1ae7.png)

**Comment by blakadder** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/6526

**Comment by MilewskiPawel** [comment]
God bless you man!
