### ISSUE TITLE
tuya general device support in ZHA

### ISSUE THREAD

**Issue by MattWestb** [blakadder/zigbee#381]
ZHA have added general support (only model name and no model info) for flowing device:
Scene switch / remotes TS0041, TS0042, TS0043, TS0044
Dimmer switch / remotes TS004F 
Cover controller TS130F.

Then the switches / remotes is coming in many different shape is it possible making one "general tuya TS0014" device (one for every type with one symbolic tuya picture) with explaining that all devices with this model is supported in ZHA and normally dont need one new quirk for working (some devices can having extra functions like back light that need being added but it possible doing with one device quirks) ?

I have seeing one general "tuya switch" but i cant finding it in the repro for the moment so i think its deleted or changed.

Thanks in advance !!

Mattias W

**Comment by MattWestb** [comment]
TS0041 https://github.com/zigpy/zha-device-handlers/pull/957
TS0042, TS0043 and TS0044 https://github.com/zigpy/zha-device-handlers/pull/958
TS004F https://github.com/zigpy/zha-device-handlers/pull/969
TS130F https://github.com/zigpy/zha-device-handlers/pull/980

**Comment by blakadder** [comment]
So how does that work if there are f.e. TS0601 covers, switches, plugs and more

**Comment by MattWestb** [comment]
All tuya TS0601 devices (_TYST11 and _TZE200 in the name) (switches, dimmers cover and so on) is using the tuya cluster and tunneling tuya (mqtt) commands to/from tuya MCU and all this devices have quirks for working in ZHA and other open systems. https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601.py

The TS130F is one more "normal" zigbee device and is using more standard zigbee clusters so its not needing and quirk for individual devices only the general TS130F and they is working out of the box if not having extra function implanted.

**Comment by blakadder** [comment]
So you're saying only the models listed in https://github.com/blakadder/zigbee/issues/381#issuecomment-905518491 are universally supported until a manufacturer creates a different device with the same model id?

**Comment by MattWestb** [comment]
See it like this:

tuya lights is good Zigbee cluster compatible and some have missing CT (LIDL) that need one device quirk like many Philips HUE is doing and so on.

The TS001X, TS004X and TS130F devices have getting model quirks that is making all of them ZCL compatible as long some manufacture is **not** adding extra functions (new model ID is OK if not messing the cluster up) that is braking some cluster, but that can being fixed with device quirk then its happening.

Most (no TS0601) switches and dimmer modules with various model id is ZCL compatible and working out of the box without quirks.

I have finding the device with only model  https://zigbee.blakadder.com/Tuya_TS0041.html
This devices and all other TS0041 is now working in ZHA then its having the model.

Adding one "tuya Scene Switch TS0041" as general is making user can finding all of this type is supported of ZHA.
