### ISSUE TITLE
M515EGB how to pair to conbee

### ISSUE THREAD

**Issue by sanderlv** [blakadder/zigbee#439]
According to https://zigbee.blakadder.com/Zemismart_M515EGB.html it is compatible with conbee. I currently use it with the dongle and do not like that. What is the procedure to pair the motor unit directly with zigbee? Where can I find more information ably that process?

Thank you in advance.

**Comment by blakadder** [comment]
if i understand correctly you don't like pairing the dongle via zigbee and you would like to pair the motor instead?

that would be a question for the manufacturer

**Comment by sanderlv** [comment]
I thought the dongle was some sort of wifi-zigbee bridge. And according to the link I provided I thought I could include the "motor" directly to deconz/conbee. That's what I prefer.

**Comment by sanderlv** [comment]
How can I unclose this question?
