### ISSUE TITLE
compatible with ?

### ISSUE THREAD

**Issue by pipiche38** [blakadder/zigbee#465]
I would like to share a comment has regards to this wonderful/awesome open source Zigbee database.

On the market today we have different application layers

- Applications like Home Assistant, Domoticz, Jeedom ....
- plugins like (ZHA) zigpy, z2m for domoticz, deconz for domoticz, Zigate for Domoticz ....
- quirks for ZHA
- middleware (for mqtt) z2m, deconz
- coordinators .......

In the current database there is potential issues that a device is tag as supported on deConz, but do not work on ZHA because there is a missing Quirks , and vice-versa it can tag as supported on ZHA (because it works with a specific Controller but not an other one)

probably soon, a plugin willbe available on Domoticz based on zigpy layer ( what is used also by ZHA), and where devices could be supported by this new plugin, while it is not supported on ZHA. I'm thinking for instance for legacy Schneider Wisers for which there is no quirks for ZHA , but will work on this up-coming plugin

So I'm wondering if it shouldn't be better to have 2 levels of compatibility

Level 1: is the application/box ( ZHA, Domoticz-Z2M, Domoticz-Zigate ....)
Level 2: is the controller

**Comment by badzz** [comment]
+1

**Comment by jp-keros** [comment]
+1

**Comment by blakadder** [comment]
> I would like to share a comment has regards to this wonderful/awesome open source Zigbee database.
> 
> On the market today we have different application layers
> 
> * Applications like Home Assistant, Domoticz, Jeedom ....
> * plugins like (ZHA) zigpy, z2m for domoticz, deconz for domoticz, Zigate for Domoticz ....
> * quirks for ZHA
> * middleware (for mqtt) z2m, deconz
> * coordinators .......
> 
> In the current database there is potential issues that a device is tag as supported on deConz, but do not work on ZHA because there is a missing Quirks , and vice-versa it can tag as supported on ZHA (because it works with a specific Controller but not an other one)

I don't understand the point here. What does deConz have to do with ZHA?
 
> probably soon, a plugin willbe available on Domoticz based on zigpy layer ( what is used also by ZHA), and where devices could be supported by this new plugin, while it is not supported on ZHA. I'm thinking for instance for legacy Schneider Wisers for which there is no quirks for ZHA , but will work on this up-coming plugin

Since the layer itself doesn't provide any compatibility it does not matter.
 
> So I'm wondering if it shouldn't be better to have 2 levels of compatibility
> 
> Level 1: is the application/box ( ZHA, Domoticz-Z2M, Domoticz-Zigate ....) Level 2: is the controller

Z2M compatibility should be identical regardless of which system its being used on since its completely independent. Seems to me, Zigate is the only one that is unnecessarily fractured and behaves differently depending on where it is used

**Comment by pipiche38** [comment]
> Z2M compatibility should be identical regardless of which system its being used on since its completely independent. Seems to me, Zigate is the only one that is unnecessarily fractured and behaves differently depending on where it is used

It is fractured as you said, because it is an Hardware controller as the zzh from Electro lama or any other controller, and it used as the same level as ZHA or Z2M, that for me which make the things very confusing

So maybe renaming zigate into DZ for Domoticz Zigate or something like this would help

**Comment by blakadder** [comment]
> > Z2M compatibility should be identical regardless of which system its being used on since its completely independent. Seems to me, Zigate is the only one that is unnecessarily fractured and behaves differently depending on where it is used
> 
> It is fractured as you said, because it is an Hardware controller as the zzh from Electro lama or any other controller, and it used as the same level as ZHA or Z2M, that for me which make the things very confusing
> 
> So maybe renaming zigate into DZ for Domoticz Zigate or something like this would help

Agreed!

**Comment by zigbeefordomoticz** [comment]
Hello,

In closed link with Zigpy team @hedda and Electrolama we are currently preparing a new plugin for Domoticz which is going to integrate the Zigate native controller but the zigpy library and will benefits from the all zigpy-<radio> collections

The foundation is based on the Zigate Plugin for Domoticz , it would be kind of you if we could you Z4D (Zigbee for Domoticz) as the Gateway

**Comment by pipiche38** [comment]
Sound good Zigbee4Domoticz is fine

**Comment by pipiche38** [comment]
@blakadder do you need some help from us to move the Zigate to Zigbee4Domoticz ?

**Comment by blakadder** [comment]
Is the move just replacing zigate to new plugin name?

**Comment by pipiche38** [comment]
> Is the move just replacing zigate to new plugin name?

I think we can go for that. You can use z4d as a short cut, and "Zigbee for Domoticz" for the long one.
There is now a clear push from the Domoticz community to bring more Zigbee Controllers ....

**Comment by blakadder** [comment]
wish you had a cooler name ;) 
i'm using domoticz icon for now since i didn't find one in the github

**Comment by pipiche38** [comment]
I have a temporary icon if you want. Plan to get a final next week
![Z4D-200](https://user-images.githubusercontent.com/8291674/148552602-f8453ad3-8cd6-4d08-bb83-9b3579ec223a.png)

**Comment by blakadder** [comment]
looks cool... a transparent version would be nice

**Comment by pipiche38** [comment]
Thanks for having started the changes.
I just notice a small issue (which I believed is linked to the changes)

1/ The name show is still Zigate
2/ The Url attached to the button is https://z4d.fr/
<img width="1378" alt="Screenshot 2022-01-11 at 15 28 34" src="https://user-images.githubusercontent.com/8291674/148961526-616ee859-1c4e-4d1e-a1f0-d2203d2165f5.png">

**Comment by pipiche38** [comment]
> looks cool... a transparent version would be nice

hello, the logos are store here, let me know if you need something else
https://github.com/zigbeefordomoticz/logo

**Comment by pipiche38** [comment]
tha nks
