### ISSUE TITLE
Mains powered devices not working as repeaters

### ISSUE THREAD

**Issue by Weldawadyathink** [blakadder/zigbee#504]
Would it be possible to add information about zigbee repeaters to the database? The website says that most mains powered devices will act as repeaters for other zigbee devices, but this is not always the case. For example, sengled outlets and bulbs do not function as repeaters (at least the ones I have). I spent weeks diagnosing zigbee issues before I figured this fact out. 

Maybe just a note on devices that don’t follow the rule?

**Comment by blakadder** [comment]
every device is editable using the "Edit" button and such notice can be added below or in the `supports` field
