### ISSUE TITLE
Mark "Nexentro Blinds Actuator Mini" as compatible with ZHA and deCONZ

### ISSUE THREAD

**Issue by cremor** [blakadder/zigbee#568]
The device "Nexentro Blinds Actuator Mini" can be marked as compatible with ZHA and deCONZ.
Device page: https://zigbee.blakadder.com/Insta_57008000.html

ZHA works out of the box - the device follows all Zigbee specification standards.
I'm using the device myself with ZHA.
But note: Tilt does not work with ZHA yet! This has nothing to do with the device, ZHA simply doesn't support tilt for any cover device yet. There are workaround available, e.g. using the `zha.issue_zigbee_cluster_command` service to directly send the `go_to_tilt_percentage` command.

deCONZ should also work out of the box for cover position. To get tilt working you seem to need this custom DDF: https://forum.phoscon.de/t/insta-nexentro-blinds-actuator-mini/687/4
I'm not using deCONZ myself but found that information while researching the device.

**Comment by blakadder** [comment]
done
