### ISSUE TITLE
API to query over internet

### ISSUE THREAD

**Issue by pipiche38** [blakadder/zigbee#588]
I'm interested to retrieve the list of devices supported by a dedicated Gateway . Is there a JS API to do so ? 

I might also be interested to query if a particular device is supported by a dedicated Gateway. Is such API exists ?

Thanks in advance

**Comment by blakadder** [comment]
I can do a json file as the base for any queries if that's ok?

**Comment by pipiche38** [comment]
This would be perfect

**Comment by pipiche38** [comment]
Otherwise, the assets/database.js looks good, as soon as you can provide also a list of compatible gateways/boxes

**Comment by blakadder** [comment]
will this be satisfactory https://zigbee.blakadder.com/devices.json

**Comment by pipiche38** [comment]
This looks perfect!
Thanks so much
