### ISSUE TITLE
Hue Impress Outdoor Wall Light RGBCCT: Confirmed working with ZHA

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [blakadder/zigbee#674]
Hi

I bought this light:
https://zigbee.blakadder.com/Philips_1743030P7.html

I can confirm that it works with ZHA integration in HA. No problems. All controls are there.
PS: Didn't know how to tell this otherwise as I have no twitter account.

Best Regards

**Comment by blakadder** [comment]
thanks, i'll update the page
