### ISSUE TITLE
Philips Hue Outdoor Sensor SML004 is now supported by deConz

### ISSUE THREAD

**Issue by Asuanin** [blakadder/zigbee#678]
Philips Hue Outdoor Sensor SML004 is supported in deConz from version 2.16.1

deConz release
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.16.1

blackadder page
https://zigbee.blakadder.com/Philips_SML004.html

**Comment by blakadder** [comment]
thanks, updated
