### ISSUE TITLE
Tuya 4 button remote TS0044 / _TZ3000_ee8nrt2l doesn‘t work with deCONZ

### ISSUE THREAD

**Issue by Pedder007** [blakadder/zigbee#685]
Tuya/Loratap 4 button remote doesn‘t work properly with deCONZ.
Please see here: 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5836

On the web page it is shown as compatible.
Maybe also my understanding on what the page means is wrong?
The device is able to be paired, but without functionality.

**Comment by blakadder** [comment]
Which web page?

**Comment by Pedder007** [comment]
Hi, this one:
https://zigbee.blakadder.com/LoraTap_SS6400ZB.html

**Comment by Pedder007** [comment]
Hi again, just would like to give feedback that meanwhile the switch is working in my deCONZ environment.
There seems having been issues while the first pairing, which I meanwhile could tackle with some nice support here on Git.
