### ISSUE TITLE
Moes ZTRV-ZX-TV01-MS seems to be described wrongly

### ISSUE THREAD

**Issue by djmaze** [blakadder/zigbee#778]
According to https://zigbee.blakadder.com/Moes_ZTRV-ZX-TV01-MS.html, the ZTRV-ZX-TV01-MS is a TuYa TS0601 and it links to the [TS0601 page device for Zigbee2MQTT](https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html). But the valve shown over there looks vastly different. 

At Moes, you can find the [ZTRV-368-MS](https://www.moeshouse.com/products/tuya-zigbee3-0-radiator-actuator-smart-programmable-thermostat-temperature-trv-controller?variant=39357552590929) which looks much more like the TS0601 shown on the Zigbee2MQTT page.

**Comment by blakadder** [comment]
Zigbee2MQTT supported devices list images are not always corresponding to the actual device look
