### ISSUE TITLE
Weima (Wima) Cylinder Door #990

### ISSUE THREAD

**Issue by remidetoulon** [blakadder/zigbee#8]
Hello,
Do you have an idea?

https://github.com/KiwiHC16/Abeille/issues/990

**Comment by blakadder** [comment]
an idea?

**Comment by remidetoulon** [comment]
Hello
sorry for my english which is not correct.
I wanted to say that we have opened an outlet for the tuya vima smart lock.
We are looking for help to decode what we have sniffed to date.
If you can put your intellectual contribution, we would be very happy.
cordially

**Comment by blakadder** [comment]
i only list already confirmed devices, i do not do protocol sniffing or decoding

**Comment by remidetoulon** [comment]
ok merci
