### ISSUE TITLE
Beok_TGR85-ZB not working/compatible ZHA

### ISSUE THREAD

**Issue by Hilpas** [blakadder/zigbee#852]
Hi,
i bought this Thermostat to use with ZHA. Unfortunately its not connecting properly, i mean it is but the only shown entities are LQI/RSSI and those arent even available.

**Comment by blakadder** [comment]
what is the model and manufacturer id?

**Comment by Hilpas** [comment]
> what is the model and manufacturer id?

TS0601 _TZE200_2ekuz3dz

Seems to be due to the newer model 2ekuz3dz having different firmware.

**Comment by blakadder** [comment]
As you can see it's part of the ZHA code https://github.com/zigpy/zha-device-handlers/blob/792d7e2ed0c40e16c7a58c9854fd0062649b6cc8/zhaquirks/tuya/ts0601_trv_sas.py#L205

You may be running an old version

**Comment by Hilpas** [comment]
> As you can see it's part of the ZHA code https://github.com/zigpy/zha-device-handlers/blob/792d7e2ed0c40e16c7a58c9854fd0062649b6cc8/zhaquirks/tuya/ts0601_trv_sas.py#L205
> 
> You may be running an old version

Using that qurik i dont get any entities. The only one that is sort of working for me is this one :
https://github.com/zigpy/zha-device-handlers/pull/1609 
but still no control. I can only see the actual temperature.
As far as i know i am running the latest versions.
