### ISSUE TITLE
Tuya energy meter with clamp TZE204

### ISSUE THREAD

**Issue by alexfd** [blakadder/zigbee#914]
Hello, I have looked at the database and cannot find this device listed:
```
"manufacturer": "_TZE204_cjbofhxw", 
"model": "TS0601",
```
https://www.aliexpress.com/i/1005004845740618.html
ZHA pairs fine but no entity/sensor is found.
Can anyone tell me if there is any quirk available for it?

**Comment by alexfd** [comment]
@blakadder can you provide some context here? Is my issue not appropriate or do you not plan to support this device?

**Comment by blakadder** [comment]
https://github.com/zigpy/zha-device-handlers
