### ISSUE TITLE
Broken link for GiEX_QT06 page?

### ISSUE THREAD

**Issue by josecarre** [blakadder/zigbee#928]
Hi, i've bought this water valve as it seems compatible with ZHA: https://zigbee.blakadder.com/GiEX_QT06.html
In that page there is a button named "configuration" and that link is broken, should go to this file? `https://github.com/blakadder/zigbee/blob/11874a3026aff6dcc991b9cf5f8dc26be5ece6d7/assets/configs/GiEX_QT06.zb`, os this is just an old file?
Is not clear for me what do i need to do with the water valve :(. My zigbee gateway is [SkyConnect](https://www.home-assistant.io/skyconnect/), coming ins some days.

**Comment by blakadder** [comment]
the button named configuration is also under a "Tasmota" heading and it doesn't apply to you

**Comment by josecarre** [comment]
> the button named configuration is also under a "Tasmota" heading and it doesn't apply to you

I understood that maybe flashing tasmota to the water valve is a requirement? or not?

**Comment by blakadder** [comment]
it is not and you cannot flash Tasmota on zigbee devices
